# Шаблон конфигурации nginx с SSL сертификатом
server {
    listen 443 ssl;
    server_name localhost;
# Сертификаты отдадим через volume mapping
    ssl_certificate     /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
